name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get latest stable Rust
        run: rustup toolchain install stable --profile minimal
      - name: Check out source
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
